image: node:latest

stages:
    - publish

publish:
    stage: publish
    script:
        # Make sure the commits are clean
        - npm ci
        - npx commitlint --from=master to=CI_BUILD_REF_NAME

        # Build the project
        - npm run build

        # Perform the automatic release process
        - npx semantic-release
